# Generated by Django 5.1.5 on 2025-02-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('speed', 'Speed'), ('accuracy', 'Accuracy')], max_length=20)),
                ('punctuality_rating', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('languages', models.JSONField()),
                ('accuracy_rating', models.FloatField(default=5.0)),
                ('speed_rating', models.FloatField(default=5.0)),
            ],
        ),
    ]
